spring:
  application:
    name: gateway-service


  main:
    web-application-type: reactive


jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn

server:
  port: 8080

authentication:
  enabled: true